name: Gerar previsão de pescaria

on:
  schedule:
    - cron: '0 4 * * *'  # Executa todos os dias às 4h da manhã UTC (~1h da madrugada no Brasil)
  workflow_dispatch:     # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Criar variável de ambiente com chave da API
        run: echo "STORMGLASS_API_KEY=${{ secrets.STORMGLASS_API_KEY }}" >> $GITHUB_ENV

      - name: Executar script
        run: python gerar_pescaria.py

      - name: Commit do HTML gerado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Previsão atualizada automaticamente" || echo "Sem alterações"
          git push
